version: 0.0
os: linux
files:
  - source: /index.html
    destination:
hooks:
  BeforeInstall:
    - location:
      timeou:
      runas: root
  ApplicationStop:
    - location:
      timeout:
      runas:
